spring.application.name=ipaas-commonservice-sap4rest
server.address=0.0.0.0
server.port=8086
management.endpoints.web.exposure.include=health,info,prometheus


camel.custom.restful=rest:post:{id}/{desName}/{rfc}
camel.custom.delCache=rest:post:del/{desName}/{rfc}
#管理系统域名地址（无/）
camel.custom.httpBase=http://localhost:8013
#DB缓存时间（分钟）
camel.custom.cache.db=1
#RFC缓存时间（分钟）
camel.custom.cache.rfc=1
#license缓存时间（分钟）
camel.custom.cache.license=5

#rest配置
#建议根据实际场景修改-连接超时:毫秒(默认180000ms)
camel.component.http.connect-timeout=180000
#建议根据实际场景修改-读取超时:毫秒(默认180000ms)
camel.component.http.so-timeout=180000
#建议根据实际场景修改-连接请求超时:从连接池获取连接的超时时间(默认180000ms)
camel.component.http.connection-request-timeout=180000
#rest配置结束


#日志配置
#日志保存地址
ipaas.logger.httpPath=http://127.0.0.1:8186/api/saveLog
#日志服务连接超时时间
ipaas.logger.connectTimeout=1000
#日志服务响应超时时间
ipaas.logger.responseTimeout=1000
#日志配置结束

#Call SAP
camel.custom.sap.destination=HDR
camel.component.sap.configuration.destinationDataStore.HDR.ashost=10.203.111.71
camel.component.sap.configuration.destinationDataStore.HDR.sysnr=00
camel.component.sap.configuration.destinationDataStore.HDR.client=810
camel.component.sap.configuration.destinationDataStore.HDR.user=ESBUSER
camel.component.sap.configuration.destinationDataStore.HDR.passwd=shanghai1
camel.component.sap.configuration.destinationDataStore.HDR.lang=EN
