spring.application.name=ipaas-commonservice-sap4rest
server.address=0.0.0.0
server.port=8086
management.endpoints.web.exposure.include=health,info,prometheus


camel.custom.restful=rest:post:{id}/{desName}/{rfc}
camel.custom.delCache=rest:post:del/{desName}/{rfc}
#管理系统域名地址（无/）
camel.custom.httpBase=http://localhost:8013
#DB缓存时间（分钟）
camel.custom.cache.db=1
#RFC缓存时间（分钟）
camel.custom.cache.rfc=1
#license缓存时间（分钟）
camel.custom.cache.license=5
#接口RSA加密私钥
camel.custom.rsa.private=MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJD5+T1j2Oi4sPNeD/Q4xaLzYhMJNq2chUzihm4PlUgxcjJB6RioIPewE9NmkuFTShWfAvckZDQ5rD07Dwye6TQPnS69FiqDDl3Yqo4/sTNbXp2w1VbE2JxbvAajFx3j961ERrKQ3cTwqDJaS/y63h6yk2WulwqVuMngTN2Zja3jAgMBAAECgYAw+E7pHqXxDhmvSvGGo/qWLTHOjkkq4XjhXI7d9GOPbCxPr5XF31yrbY101ev9Mn4OyZRd2KwEPAri7+UIdVD94lSGuruBpQ9YhyB7hsl1+iaNax7JC58EAy/JUye9UbRPTovkknbL1jgsAXMoGo3AQjRSdKherBdqNvcxu2UN8QJBAKaLC674SxRTF+d9a0/dgHEG2o5MzpLPSahW4/m3utm9xvdCZxCa7wwpJMnU0oQwYDCfuz07PXAyrY2qPEX5j9sCQQDe2Vf+ZeQk7Y9NBS+G/BWWQJefPayPhZv+RsvTWbcA6NtFJpT0IbBI/YqOYcyUlTfmLF6mecW3iMo/B2q/XFyZAkBb3LRcFZ6sHk1AJcDsc5wmPAaPmTQUbHwPe6YSFtLcyb4WoqzgzuTuSz98iIR534kfKOwJkUSJP5rVWkIWwtojAkEAiFZSRlrR9GG+fTGB/UR2dIE6Aft6eigU4sEvbDOECbNsiubq1F1T+6PaQ/fDcNfF5jUZByKS+xFeIqeIAGEiaQJAFu+aFZNkMsuInD5wPu70GC0HZFr/5qh6Y8dvgRCjy7Ix+pzQkG/al5TRHWDzIHS8iuszgyMeOs7MJP3DaYArug==
#开放接口简单校验凭证
camel.custom.rest.token=qwerasdzxc

#日志配置
#日志保存地址
ipaas.logger.httpPath=http://127.0.0.1:8186/api/saveLog
#日志服务连接超时时间
ipaas.logger.connectTimeout=1000
#日志服务响应超时时间
ipaas.logger.responseTimeout=1000
#日志配置结束

#Call SAP
camel.custom.sap.destination=HDR
camel.component.sap.configuration.destinationDataStore.HDR.ashost=10.203.111.71
camel.component.sap.configuration.destinationDataStore.HDR.sysnr=00
camel.component.sap.configuration.destinationDataStore.HDR.client=810
camel.component.sap.configuration.destinationDataStore.HDR.user=ESBUSER
camel.component.sap.configuration.destinationDataStore.HDR.passwd=shanghai1
camel.component.sap.configuration.destinationDataStore.HDR.lang=EN
